### ISSUE TITLE
Cannot read property 'isDirectory' of undefined

### ISSUE THREAD

**Issue by lifeart** [stfsy/broccoli-plugin-adapter#12]
![image](https://user-images.githubusercontent.com/1360552/130141257-8ed9ba1f-79d1-44cd-a723-a15b16a3299c.png)

looks like in some cases https://github.com/stfsy/broccoli-plugin-adapter/blob/master/lib/index.js#L40 may be undefined

because entries.length could be 0

```this._processNextDirectoryEntry(fs, entries = [], 0, folder)```

**Comment by stfsy** [comment]
hi @lifeart thanks for reporting this. Sounds like in this case we could just return earlier. 🙂

Will have a look tomorrow.

**Comment by stfsy** [comment]
@lifeart should be fixed with https://github.com/stfsy/broccoli-plugin-adapter/releases/tag/v1.4.1.

May I ask what you're using this library for? Haven't come across an users yet 🙂

**Comment by lifeart** [comment]
@stfsy for custom live-reload middleware, I was thinking it able to detect changed files and process it’s selectively, but, it seems we have to read all files to not break broccoli pipeline and
at this point I little bit disappointed in Broccoli, because there is no way to skip file reading (coping from input to output). As I understand, symlinking could work, in theory, but I unable to find references for it
